services:
  - type: web
    name: loop-backend
    env: python
    region: singapore
    plan: free
    rootCommand: cd backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
    autoDeploy: true
